export const PGMQ_CONNECTION = 'PGMQ_CONNECTION';
export const PGMQ_MODULE_OPTIONS = 'PGMQ_MODULE_OPTIONS';

export const PGMQ_PROCESSOR_METADATA = 'PGMQ_PROCESSOR_METADATA';
export const PGMQ_PROCESS_METADATA = 'PGMQ_PROCESS_METADATA';
