name: Publish to NPM
on:
  release:
    types: [published]

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - uses: actions/setup-node@v5
        with:
          cache: 'pnpm'

      - run: pnpm install
      - run: pnpm --filter nestjs-pgmq build

      - run: npm publish --provenance --access public
        working-directory: packages/nestjs-pgmq
